
Machine !!LoadFile: 'ArithmeticTests.st'.
Machine !!LoadFile: 'ArrayListTests.st'.
Machine !!LoadFile: 'BooleanTests.st'.
Machine !!LoadFile: 'CharTests.st'.
Machine !!LoadFile: 'EnvironmentTests.st'.
Machine !!LoadFile: 'IntegerTests.st'.
Machine !!LoadFile: 'ObjectTests.st'.
Machine !!LoadFile: 'SmalltalkTests.st'.
Machine !!LoadFile: 'StringTests.st'.
Machine !!LoadFile: 'WebServer.st'.
Machine !!LoadFile: 'WebServerTests.st'.